CFLAGS=-Wall -Werror -Wextra -pedantic -g -std=gnu89

0-main: *.c test/0-main.c
	gcc  $(CFLAGS) $^ -o $@

1-main: *.c test/1-main.c
	gcc  $(CFLAGS) $^ -o $@

2-main: *.c test/2-main.c
	gcc  $(CFLAGS) $^ -o $@

3-main: *.c test/3-main.c
	gcc  $(CFLAGS) $^ -o $@

4-main: *.c test/4-main.c
	gcc  $(CFLAGS) $^ -o $@

